
#' Hommola correlation with permutation significance testing
#'
#' Calculates Hommola correlation coefficient and p-value by comparing the
#' observed correlation to a null distribution generated by random permutations
#' of the host-symbiont association while preserving the symbiont distance matrix.
#'
#' The symbiont distance matrix is melted once and reused across all
#' permutations; each permutation only re-maps symbionts to hosts and indexes
#' into the host distance matrix, which makes the permutation loop substantially
#' faster than recomputing the full reshape each time.
#'
#' @param i_host_subtree_dist A distance matrix for host subtree tips
#' @param i_symbiont_subtree_dist A distance matrix for symbiont subtree tips
#' @param i_host_to_symbiont_df A data frame with "Host" and "Symbiont" columns
#' @param permutations Number of random permutations for null distribution;
#'   at least 99 recommended
#' @param seed Random seed for reproducibility; if NA, no seed is set
#'
#' @return A list with two elements:
#'   - Uncollapsed_Hommola_r: The observed correlation coefficient
#'   - Uncollapsed_Hommola_pvalue: One-tailed p-value (# permutations with r >= observed + 1)
#'     / (total permutations + 1)
#'
#' @export
#'
#' @examples
#' \donttest{
#' library(adephylo)
#' h_tree <- ape::rtree(5)
#' s_tree <- ape::rtree(15)
#' hs_df <- data.frame(
#'   Host = rep(h_tree$tip.label, 3),
#'   Symbiont = s_tree$tip.label
#' )
#' h_dist <- distTips(h_tree, method = "patristic")
#' s_dist <- distTips(s_tree, method = "patristic")
#' result <- hommola_wf(h_dist, s_dist, hs_df, permutations = 99, seed = 123)
#' }
#'
hommola_wf <- function(i_host_subtree_dist, i_symbiont_subtree_dist,
                       i_host_to_symbiont_df, permutations, seed) {

  # PERFORMANCE: melt the symbiont distances once; this reshape is identical
  # across every permutation and was previously recomputed each time.
  sym <- .melt_dist(i_symbiont_subtree_dist)
  host_mat <- .as_labelled_matrix(i_host_subtree_dist)
  host_labels <- i_host_to_symbiont_df$Host
  symbiont_labels <- i_host_to_symbiont_df$Symbiont

  # observed correlation
  hommola_res <- .hommola_core(sym, host_mat, symbiont_labels, host_labels)

  # PERMUTATION
  # Shuffle the symbiont-to-host link while preserving the distribution of
  # genetic distances. Each column of permutations_mat is one reshuffling of
  # the symbiont labels relative to the (fixed) host labels. All permutation
  # correlations are computed at once with integer indexing.
  # Seeding is done locally: the caller's global RNG state is restored on exit
  # so this function has no random-number side effects.
  if (!is.na(seed)) {
    if (exists(".Random.seed", envir = .GlobalEnv)) {
      old_seed <- get(".Random.seed", envir = .GlobalEnv)
      on.exit(assign(".Random.seed", old_seed, envir = .GlobalEnv), add = TRUE)
    } else {
      on.exit(suppressWarnings(rm(".Random.seed", envir = .GlobalEnv)), add = TRUE)
    }
    set.seed(seed)
  }
  n <- nrow(i_host_to_symbiont_df)
  permutations_mat <- replicate(permutations, sample(n))

  perm_vals <- .hommola_perm_cors(sym, host_mat, symbiont_labels, host_labels,
                                  permutations_mat)

  p_value <- (sum(perm_vals >= hommola_res) + 1) / (permutations + 1)

  list(Uncollapsed_Hommola_r = hommola_res, Uncollapsed_Hommola_pvalue = p_value)
}
